added text, button and background
PalmiraBenavente/ParkingSystemJava pull request #1
Opened 2021-06-14 20:19 UTC by PalmiraBenavente

added text, button and background

<img width="176" alt="Carpetas" src="https://user-images.githubusercontent.com/84336438/121953718-4ab06600-cd34-11eb-9f64-76f6c46357e8.png">
<img width="205" alt="pantalla" src="https://user-images.githubusercontent.com/84336438/121953722-4be19300-cd34-11eb-8c0b-aab04039596f.png">

2021-06-14 20:25 UTC, mauroLonghi commented on app/src/main/res/layout/activity_main.xml
> +
Pls remove unnecessary empty spaces

2021-06-14 20:27 UTC, mauroLonghi commented
Palmi, convert the image .png to .webp

2021-06-14 20:36 UTC, nicolbidone requested changes

2021-06-14 20:36 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button3"
please give to the id a more representative name

2021-06-14 21:10 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +</LinearLayout>
to fix this you should apply `File > Preferences > Editor > General > Ensure line feed at file end on Save` at Android Studio

2021-06-14 23:19 UTC, mauroLonghi commented
In the structure image you have two files theme, why?

2021-06-15 13:33 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_main.xml
> +
Done

2021-06-15 13:33 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button3"
Done

2021-06-15 13:34 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_main.xml
> +</LinearLayout>
Done

2021-06-15 13:47 UTC, lucianoeli commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/button_main_margin_top_big</item>
its not recomended to add margins on styless

2021-06-15 13:49 UTC, SartiMau requested changes

2021-06-15 13:49 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +</LinearLayout>
this still here ;)

2021-06-15 13:49 UTC, SartiMau commented on app/src/main/res/values/colors.xml
>  </resources>
add an empty line at the end of the file to avoid this error

2021-06-15 13:49 UTC, SartiMau commented on app/src/main/res/values/dimens.xml
> +</resources>
add an empty line at the end of the file to avoid this error

2021-06-15 13:49 UTC, SartiMau commented on app/src/main/res/values/strings.xml
>  </resources>
add an empty line at the end of the file to avoid this error

2021-06-15 13:49 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +</resources>
add an empty line at the end of the file to avoid this error

2021-06-15 13:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/button_main_margin_top_big</item>
if all the buttons will be use the same style I think it is okay ;)

2021-06-15 13:54 UTC, lucianoeli commented on app/src/main/res/values/styles.xml
> +</resources>
once you setted Android studio like nico said, ensure to format code `ctrl + alt + L` on all files :)

2021-06-15 14:23 UTC, PalmiraBenavente commented on app/src/main/res/values/colors.xml
>  </resources>
Done

2021-06-15 14:23 UTC, PalmiraBenavente commented on app/src/main/res/values/dimens.xml
> +</resources>
Done

2021-06-15 14:23 UTC, PalmiraBenavente commented on app/src/main/res/values/strings.xml
>  </resources>
Done

2021-06-15 14:23 UTC, PalmiraBenavente commented on app/src/main/res/values/styles.xml
> +</resources>
Done

2021-06-15 14:45 UTC, lucianoeli approved these changes

2021-06-15 14:57 UTC, SartiMau requested changes

2021-06-15 14:57 UTC, SartiMau commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_text_size_big">25dp</dimen>
all the text text sizes should be in sp

2021-06-15 15:05 UTC, PalmiraBenavente commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_text_size_big">25dp</dimen>
Done

2021-06-15 15:10 UTC, SartiMau approved these changes

2021-06-16 12:45 UTC, BQuinteros approved these changes

2021-06-16 12:56 UTC, nicolbidone approved these changes

2021-06-16 13:14 UTC, mauroLonghi approved these changes

2021-06-16 14:07 UTC, lucianoeli approved these changes

2021-06-16 14:09 UTC, merged