added functionality pressed button
PalmiraBenavente/ParkingSystemJava pull request #2
Opened 2021-06-17 16:03 UTC by PalmiraBenavente

- MVP implementation
- Added contract, model, presenter and view files and folders
- Added String for the Toast message in values -> strings
- Added viewBinding in Gladle.

![image](https://user-images.githubusercontent.com/84336438/122433072-42db0680-cf6c-11eb-8e95-b3aaf84210b9.png)
![image](https://user-images.githubusercontent.com/84336438/122433103-48d0e780-cf6c-11eb-829d-078f76e2c0dd.png)

- Added base folder
![image](https://user-images.githubusercontent.com/84336438/122573271-fa335400-d024-11eb-8246-deecf989c769.png)

2021-06-17 16:10 UTC, mauroLonghi approved these changes

2021-06-17 16:14 UTC, lucianoeli commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +    @SuppressLint("StringFormatInvalid")
is this really necesary? delete if not please

2021-06-17 16:16 UTC, lucianoeli commented on app/src/main/java/com/example/parkingsystem/mvp/view/ActivityView.java
> +
delete this emptty lines please.
you can configure AS fort that

2021-06-17 16:22 UTC, lucianoeli commented on app/src/main/java/com/example/parkingsystem/mvp/view/ActivityView.java
> +
check other files too please

2021-06-17 17:10 UTC, SartiMau requested changes

2021-06-17 17:10 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ActivityView.java
> +package com.example.parkingsystem.mvp.view;
this class should be in a base package inside the view package

2021-06-17 17:10 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +    @SuppressLint("StringFormatInvalid")
Please delete this SuppressLint try to fix the warning in another way. I'm not sure if it is necessary

2021-06-18 13:55 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +    @SuppressLint("StringFormatInvalid")
Done

2021-06-18 13:56 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ActivityView.java
> +
Done

2021-06-18 13:56 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ActivityView.java
> +package com.example.parkingsystem.mvp.view;
Done

2021-06-18 14:09 UTC, SartiMau approved these changes

2021-06-18 14:49 UTC, lucianoeli approved these changes

2021-06-18 14:58 UTC, merged