Palmira.benavente/implementation dialog fragment
PalmiraBenavente/ParkingSystemJava pull request #3
Opened 2021-06-25 16:53 UTC by PalmiraBenavente

- Dialog fragment implementation: Added contract, model, view and presenter for the dialog fragment.
- Added layout, styles, dimensions, color, strings for DialogFragment.

![image](https://user-images.githubusercontent.com/84336438/123457608-75af7b00-d5ba-11eb-9c77-b5fc02fef87d.png)
![image](https://user-images.githubusercontent.com/84336438/123457618-78aa6b80-d5ba-11eb-9325-bcb86d86b60e.png)
![image](https://user-images.githubusercontent.com/84336438/123457628-7d6f1f80-d5ba-11eb-997e-82ea8e4bbc67.png)

2021-06-25 17:08 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogSpaceParkingPresenter.java
> +        String str = view.getSpacesFromEditText();
rename the variable please

2021-06-25 17:09 UTC, mauroLonghi commented on app/src/main/res/layout/fragment_dialog_space_parking.xml
> +        />
pls put the end tag in the previous sentences

2021-06-25 17:38 UTC, SartiMau requested changes

2021-06-25 17:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogSpaceParkingPresenter.java
> +    private ListenerDialogFragment listenerDialogFragment;
do not save the listener as an instance variable.. just pass it as a parameter when you need it

2021-06-25 17:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +        view.toastShowSpaces(spaces);
you should get the info from the model
`        view.toastShowSpaces(getSpaces());`

2021-06-25 17:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +    private WeakReference<SpacesParkingDialogFragment> dialogFragmentWeakRef;
create a FragmentView in the base package for the weakReferences and the general things, just like the ActivityView

2021-06-25 17:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +        Toast.makeText(getContext(), getContext().getString(R.string.toast_main_activity_select_space_parking, parkingSpace),Toast.LENGTH_SHORT).show();
please, validate that the getContext is not null

2021-06-25 18:29 UTC, lucianoeli commented on app/src/main/java/com/example/parkingsystem/SpacesParkingDialogFragment.java
> +        dialogFragment.setArguments(bumble);
this is not needed. Dont make sense to send an empty bundle

2021-06-28 13:37 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogSpaceParkingPresenter.java
> +        String str = view.getSpacesFromEditText();
Done

2021-06-28 13:37 UTC, PalmiraBenavente commented on app/src/main/res/layout/fragment_dialog_space_parking.xml
> +        />
Done

2021-06-28 13:37 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogSpaceParkingPresenter.java
> +    private ListenerDialogFragment listenerDialogFragment;
Done

2021-06-28 13:37 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +        view.toastShowSpaces(spaces);
Done

2021-06-28 13:38 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +    private WeakReference<SpacesParkingDialogFragment> dialogFragmentWeakRef;
Done

2021-06-28 13:38 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +        Toast.makeText(getContext(), getContext().getString(R.string.toast_main_activity_select_space_parking, parkingSpace),Toast.LENGTH_SHORT).show();
Done

2021-06-28 13:38 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/SpacesParkingDialogFragment.java
> +        dialogFragment.setArguments(bumble);
Done

2021-06-28 14:12 UTC, SartiMau requested changes

2021-06-28 14:12 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +        SpacesParkingDialogFragment dialogFragmentReference = getParkingFragment();
here you should validate that the dialogFragmentReference is not null before using it

2021-06-28 14:12 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +            Toast.makeText(getContext(), getContext().getString(R.string.toast_main_activity_select_space_parking, parkingSpace), Toast.LENGTH_SHORT).show();
do not call again getContext() just save the context into a variable and use the variable. If you do it like this the getContext() can still be null

2021-06-28 14:12 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/base/FragmentView.java
> +    private WeakReference<SpacesParkingDialogFragment> dialogFragmentWeakRef;
this should be Fragment type

2021-06-28 14:18 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +        SpacesParkingDialogFragment dialogFragmentReference = getParkingFragment();
Done

2021-06-28 14:18 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +            Toast.makeText(getContext(), getContext().getString(R.string.toast_main_activity_select_space_parking, parkingSpace), Toast.LENGTH_SHORT).show();
Done

2021-06-28 14:18 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/base/FragmentView.java
> +    private WeakReference<SpacesParkingDialogFragment> dialogFragmentWeakRef;
Done

2021-06-28 14:32 UTC, SartiMau approved these changes

2021-06-28 14:34 UTC, BQuinteros approved these changes

2021-06-28 14:44 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogSpaceParkingPresenter.java
> +        String str = view.getSpacesFromEditText();
still here

2021-06-28 14:49 UTC, lucianoeli approved these changes

2021-06-28 15:17 UTC, mauroLonghi approved these changes

2021-06-28 15:41 UTC, merged