Palmira.benavente/reservation UI
PalmiraBenavente/ParkingSystemJava pull request #4
Opened 2021-07-01 17:43 UTC by PalmiraBenavente

Added reservation Ui 

- added activity with its mvp, contract and layout
- added dialog fragment with date and time picker
- adaptation the layout fragment to view in Nexus S

![image](https://user-images.githubusercontent.com/84336438/124166793-adfeff80-da79-11eb-8c2d-eb2642ddc353.png)

Nexus
![image](https://user-images.githubusercontent.com/84336438/124166865-c1aa6600-da79-11eb-9613-148e7633875c.png)
![image](https://user-images.githubusercontent.com/84336438/124166884-c7a04700-da79-11eb-8b07-753ea24d585e.png)
![image](https://user-images.githubusercontent.com/84336438/124166945-d38c0900-da79-11eb-92b3-a410498cd535.png)

Pixel 3a
![image](https://user-images.githubusercontent.com/84336438/124167013-e3a3e880-da79-11eb-9084-9bcd975c9440.png)
![image](https://user-images.githubusercontent.com/84336438/124167600-9411ec80-da7a-11eb-9c70-c0ae0160b2ac.png)
![image](https://user-images.githubusercontent.com/84336438/124167025-e9013300-da79-11eb-8738-7f8cdcbd29d3.png)

2021-07-01 18:26 UTC, BQuinteros commented on app/src/main/java/com/example/parkingsystem/activities/ParkingReservationActivity.java
> +        Intent intent = new Intent(context, ParkingReservationActivity.class);
here you can return the instance without putting in a variable before

2021-07-01 18:26 UTC, BQuinteros commented on app/src/main/java/com/example/parkingsystem/fragments/DateReservationDialogFragment.java
> +        DateReservationDialogFragment dataReservationDialogFragment = new DateReservationDialogFragment();
here too you can put
`return new DateReservationDialogFragment();`

2021-07-01 18:34 UTC, SartiMau requested changes

2021-07-01 18:34 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +import com.example.parkingsystem.fragments.SpacesParkingDialogFragment;
are you using this import?

2021-07-01 18:34 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/fragments/SpacesParkingDialogFragment.java
> +import com.example.parkingsystem.mvp.contract.DialogSpaceParkingContract;
are you using this import?

2021-07-01 18:34 UTC, SartiMau commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +
remove this extra line pls. Does this compile?

2021-07-01 18:34 UTC, SartiMau commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +        android:inputType="number"
android:background, android:layout_marginHorizontal and android:inputType can be on the style

2021-07-01 18:34 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +        <item name="android:background">@color/amaranth_purple</item>
an style with only one property do not make sense, please remove it

2021-07-01 18:36 UTC, mauroLonghi commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +        android:inputType="number"
inputType to

2021-07-02 14:07 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/activities/ParkingReservationActivity.java
> +        Intent intent = new Intent(context, ParkingReservationActivity.class);
Done

2021-07-02 14:07 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/fragments/DateReservationDialogFragment.java
> +        DateReservationDialogFragment dataReservationDialogFragment = new DateReservationDialogFragment();
Done

2021-07-02 14:08 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogSpaceParkingView.java
> +import com.example.parkingsystem.fragments.SpacesParkingDialogFragment;
Yes, I use it in the previous task to implement the dismiss of the DialogFragmnet that sets the number of spaces

2021-07-02 14:11 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/fragments/SpacesParkingDialogFragment.java
> +import com.example.parkingsystem.mvp.contract.DialogSpaceParkingContract;
Yes, I use this import for the presenter variable, at the time of creating the variable I do `DialogSpaceParkingContract.DialogFragmentPresenter`

2021-07-02 14:11 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +
Done

2021-07-02 14:11 UTC, PalmiraBenavente commented on app/src/main/res/values/styles.xml
> +        <item name="android:background">@color/amaranth_purple</item>
Done

2021-07-02 14:38 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +        android:inputType="number"
when I move the horizontal margin I get an error,` `android: layout_marginHorizontal` requires API level 26 (current min is 23)`, the solution was to change to marginStart and marginEnd, is there any other solution or recommendation?

2021-07-02 14:50 UTC, mauroLonghi approved these changes

2021-07-02 15:16 UTC, nicolbidone commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        dateDialogFragment.show(fragmentManager, "dialog_fragment_date_picker");
this string should be on a const

2021-07-02 15:16 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        android:text="@string/button_main_activity_reservation" />
text id and button id should be cohesive
if button_main_book_parking_spaces
android:text should be main_book_parking_spaces

2021-07-02 15:16 UTC, nicolbidone commented on app/src/main/res/layout/fragment_dialog_date_picker.xml
> +        tools:ignore="MissingConstraints">
here you can reduce layouts by using scroll view as base layout

2021-07-02 15:16 UTC, nicolbidone commented on app/src/main/res/values/strings.xml
> +    <string name="text_edit_reserver_parking_code">    ENTER THE CODE HERE...</string>
don't force spaces please use edit text properties

2021-07-02 15:50 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        dateDialogFragment.show(fragmentManager, "dialog_fragment_date_picker");
Done

2021-07-02 15:52 UTC, PalmiraBenavente commented on app/src/main/res/layout/activity_main.xml
> +        android:text="@string/button_main_activity_reservation" />
Done, I tried to make the change in all the names that I saw, I will keep it in mind more for the future

2021-07-02 15:52 UTC, PalmiraBenavente commented on app/src/main/res/values/strings.xml
> +    <string name="text_edit_reserver_parking_code">    ENTER THE CODE HERE...</string>
Done

2021-07-02 15:58 UTC, PalmiraBenavente commented on app/src/main/res/layout/fragment_dialog_date_picker.xml
> +        tools:ignore="MissingConstraints">
Done

2021-07-02 18:58 UTC, lucianoeli commented on app/src/main/res/layout/fragment_dialog_date_picker.xml
> +    tools:ignore="MissingConstraints">
shoud not use this. you are hiding warnings.
try to fix them please.

2021-07-02 18:59 UTC, lucianoeli approved these changes

2021-07-05 13:02 UTC, lucianoeli approved these changes

2021-07-05 13:04 UTC, PalmiraBenavente commented on app/src/main/res/layout/fragment_dialog_date_picker.xml
> +    tools:ignore="MissingConstraints">
Done

2021-07-05 13:28 UTC, SartiMau commented on app/src/main/res/layout/activity_reserver_parking_lot.xml
> +        android:inputType="number"
okay, it is fine, just keep the android:layout_marginHorizontal in the view XML or add the other margins to the style

2021-07-05 13:31 UTC, SartiMau requested changes

2021-07-05 13:31 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    private final String dialogFragmentDatePicker = "dialog fragment date picker";
remember that the constants should be in upper case and with words separated by _
`private final String DIALOG_FRAGMENT_DATE_PICKER = "dialog fragment date picker";`

2021-07-05 13:34 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    private final String dialogFragmentDatePicker = "dialog fragment date picker";
Done

2021-07-05 13:36 UTC, mauroLonghi approved these changes

2021-07-05 13:36 UTC, SartiMau approved these changes

2021-07-05 13:38 UTC, BQuinteros approved these changes

2021-07-05 13:46 UTC, nicolbidone approved these changes

2021-07-05 13:47 UTC, merged