Palmira.benavente/save reservation
PalmiraBenavente/ParkingSystemJava pull request #5
Opened 2021-07-06 17:07 UTC by PalmiraBenavente

Save Reservation

- added funcionality for saving the reservation in a single class database.
- added mvp funcionality to dialogFragment Picker
- added class Reservation to join the information of reservation 
![image](https://user-images.githubusercontent.com/84336438/124639984-29d6be80-de63-11eb-9bed-06cdd18608d8.png)
![image](https://user-images.githubusercontent.com/84336438/124639999-30653600-de63-11eb-940b-defd9cb7f358.png)
![image](https://user-images.githubusercontent.com/84336438/124640015-33602680-de63-11eb-8beb-60d131840f17.png)

2021-07-06 17:44 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/listener/ListenerDialogFragmentDate.java
> +    void setEndDateTime(Calendar calendarDateTime);
both method I thing that do the same no?

2021-07-06 17:45 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/model/ReservationParkingModel.java
> +    }
the validation off a reserve not be implemented in this PR , pls move it

2021-07-06 17:48 UTC, mauroLonghi commented
Pls include a video to validate the right flow on the app.
How are you showing the date-time information? pls include any image

2021-07-07 14:35 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/listener/ListenerDialogFragmentDate.java
> +    void setEndDateTime(Calendar calendarDateTime);
yes but no, each method follows the flow of each date, at the moment I can't think of how to unify them

2021-07-07 14:39 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/model/ReservationParkingModel.java
> +    }
I removed this, done, the moment I did it, beyond the vadilation, in the next task, I thought that nulls could not be saved in the base independently of if they stepped or some other question

2021-07-07 15:33 UTC, lucianoeli approved these changes

2021-07-07 15:48 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/entity/Reservation.java
> +        this.endDate = null;
pls, not assign a null in any field, instead off use an empty string

2021-07-07 15:49 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogDateResarvationView.java
> +                binding.datePickerDialogFragment.getMonth() - 1,
not use hardcodes pls

2021-07-07 15:50 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    private final int INT_MINUS_ONE = -1;
I think that i saw this constant ... use a global static final int and replace in all the places pls

2021-07-07 15:53 UTC, mauroLonghi commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    }
Could you use a generic method to unify the toast display?

2021-07-07 16:16 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    }
Done

2021-07-07 16:16 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/DialogDateResarvationView.java
> +                binding.datePickerDialogFragment.getMonth() - 1,
Done

2021-07-07 16:39 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/entity/Reservation.java
> +        this.endDate = null;
Done

2021-07-07 16:40 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +    private final int INT_MINUS_ONE = -1;
Done

2021-07-07 16:43 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/listener/ListenerDialogFragmentDate.java
> +    void setEndDateTime(Calendar calendarDateTime);
Done

2021-07-07 17:01 UTC, BQuinteros approved these changes

2021-07-07 17:56 UTC, mauroLonghi approved these changes

2021-07-08 12:17 UTC, SartiMau requested changes

2021-07-08 12:17 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ReservationParkingPresenter.java
> +        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh: mm a dd-MMM-yyyy");
do not hardcode, this string format should be into a constant

2021-07-08 12:17 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        if (lot.isEmpty()) {
this logic shoudl be in the presenter, not here

2021-07-08 12:17 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        if (code.isEmpty()) {
same

2021-07-08 12:17 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogDateResarvationPresenter.java
> +        this.startDatePicker = startDatePicker;
why do you need this in the constructor?

2021-07-08 13:12 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ReservationParkingPresenter.java
> +        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh: mm a dd-MMM-yyyy");
Done

2021-07-08 13:12 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/DialogDateResarvationPresenter.java
> +        this.startDatePicker = startDatePicker;
Done

2021-07-08 13:22 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        if (lot.isEmpty()) {
Done

2021-07-08 13:22 UTC, PalmiraBenavente commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +        if (code.isEmpty()) {
Done

2021-07-08 13:38 UTC, SartiMau requested changes

2021-07-08 13:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ReservationParkingPresenter.java
> +        } else model.setEndDate(this.getStringDate(calendarDateTime));
remember to use the curly brackets pls

2021-07-08 13:38 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ReservationParkingView.java
> +            getActivity().finish();
here you have to use the activity variable that is the one that you know that is not null

2021-07-08 14:41 UTC, SartiMau approved these changes

2021-07-08 14:41 UTC, merged